---
project_name: bridge

archives:
  - id: bridge
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      386:    32bit
      amd64:  64bit
      darwin: macOS
      linux:  Linux

brews:
  - name: bridge
    caveats:
    commit_author:
      name:  Kamil Samigullin
      email: kamil@samigullin.info
    description: A bridge between the protobuf and the brief formats.
    folder: Formula
    homepage: https://github.com/kamilsk/bridge
    github:
      owner: kamilsk
      name:  homebrew-tap
    install: |
      bin.install "bridge"
      output = Utils.popen_read("#{bin}/bridge completion bash")
      (bash_completion/bridge).write output
      output = Utils.popen_read("#{bin}/bridge completion zsh")
      (zsh_completion/_bridge).write output
      prefix.install_metafiles
    test: |
      system "#{bin}/bridge version"

builds:
  - id: bridge
    binary: bridge
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - 386
      - amd64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: kamilsk
    name:  bridge
